AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  KinesisTrigger:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: python_code/
      Handler: process_stream.handler
      Runtime: python3.7
      Timeout: 10
      Environment:
        Variables:
          STATE_M_ARN: !Ref WebHookStateMachine
      Events:
        Stream:
          Type: Kinesis
          Properties:
            Stream: !GetAtt stream.Arn
            BatchSize: 100
            StartingPosition: LATEST
  CheckIdentityFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: python_code/
      Handler: check_identity.handler
      Runtime: python3.7
  CheckAddressFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: python_code/
      Handler: check_address.handler
      Runtime: python3.7
  stream:
    Type: AWS::Kinesis::Stream
    Properties:
      ShardCount: 1
  WebHookStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachine/kinesis_demo.json
      DefinitionSubstitutions:
        CheckAddressFunctionArn: !GetAtt CheckAddressFunction.Arn
        CheckIdentityFunctionArn: !GetAtt CheckIdentityFunction.Arn
        FollowUpTableName: !Ref FollowUpTable
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref CheckAddressFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref CheckIdentityFunction
        - DynamoDBWritePolicy:
            TableName: !Ref FollowUpTable
        - EventBridgePutEventsPolicy:
            EventBusName: default
        - ComprehendBasicAccessPolicy: {}
  FollowUpTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: 'PK'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'PK'
          KeyType: 'HASH'
      BillingMode: PAY_PER_REQUEST
Outputs:
  FunctionName:
    Description: "Function name"
    Value: !Ref KinesisTrigger
  StreamARN:
    Description: "Stream ARN"
    Value: !GetAtt stream.Arn