version: '3.4'

services:
  python_services:
    stdin_open: true
    tty: true 
    volumes:
        - ./python_code:/python_code
    environment:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN
      - AWS_SECURITY_TOKEN=$AWS_SECURITY_TOKEN
    env_file:
    - ../infra/environments/.env_dev
    build:
      context: .
      dockerfile: ./Dockerfile
    entrypoint: /bin/sh
    ports:
      - 8000:8000
      - 5678:5678